The following code is written by Zhizuo Chen (aka George Chen).

It pre-processes the data file "train_sent_emo_dya.csv":

https://github.com/declare-lab/MELD/blob/master/data/MELD_Dyadic/train_sent_emo_dya.csv

In [1]:
import numpy as np, pandas as pd, time, math, random, scipy
from collections import OrderedDict
from sklearn.preprocessing import LabelEncoder

In [2]:
#Function to change timestamps in "HH:MM:SS,mmm" to miliseconds.
def timestamp2int(time_stamp_str):

    #Get the hour, minute, second, and millisecond.
    hour, minute, rest = time_stamp_str.split(':')
    second, millisecond = rest.split(',')
    #Get the second in float format.
    return 1000 * (3600 * int(hour) + 60 * int(minute) + int(second)) + int(millisecond)
    #func-end

In [3]:
#Read the data.
df = pd.read_csv("train_sent_emo_dya.csv", header = 0)
#Transform the 'StartTime' and 'EndTime' to float numbers.
df['StartTime_int'] = df['StartTime'].apply(timestamp2int)
df['EndTime_int'] = df['EndTime'].apply(timestamp2int)
#Show the data.
df.head()

,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Old_Dialogue_ID,Old_Utterance_ID,Season,Episode,StartTime,EndTime,StartTime_int,EndTime_int
0,also I was the point person on my company’s tr...,Chandler,neutral,neutral,0,0,0,0,8,21,"00:16:16,059","00:16:21,731",976059,981731
1,You must’ve had your hands full.,The Interviewer,neutral,neutral,0,1,0,1,8,21,"00:16:21,940","00:16:23,442",981940,983442
2,That I did. That I did.,Chandler,neutral,neutral,0,2,0,2,8,21,"00:16:23,442","00:16:26,389",983442,986389
3,So let’s talk a little bit about your duties.,The Interviewer,neutral,neutral,0,3,0,3,8,21,"00:16:26,820","00:16:29,572",986820,989572
4,My duties? All right.,Chandler,surprise,positive,0,4,0,4,8,21,"00:16:34,452","00:16:40,917",994452,1000917

In [4]:
#Drop irrelavant columns.
df.drop(columns = ['Sentiment', 'Dialogue_ID', 'Utterance_ID', 'Old_Dialogue_ID', 'Old_Utterance_ID', 'StartTime', 'EndTime'], inplace = True)
#Move the 'Utterance' column to the last. 
col = df.pop('Utterance')
df.insert(len(df.columns), 'Utterance', col)
#Drop duplicates.
df.drop_duplicates(inplace = True)
#Show the data.
df.head()

,Speaker,Emotion,Season,Episode,StartTime_int,EndTime_int,Utterance
0,Chandler,neutral,8,21,976059,981731,also I was the point person on my company’s tr...
1,The Interviewer,neutral,8,21,981940,983442,You must’ve had your hands full.
2,Chandler,neutral,8,21,983442,986389,That I did. That I did.
3,The Interviewer,neutral,8,21,986820,989572,So let’s talk a little bit about your duties.
4,Chandler,surprise,8,21,994452,1000917,My duties? All right.

In [5]:
#Check the speakers.
dfv = df.values
#The new list.
n_dfv = list()
#The count of all names.
nam_ct_d = OrderedDict()

#Loop through all rows.
for row in dfv:
    #Get the speaker name.
    spk_nam = row[0]
    #In the case of 'Joey/Drake', drop the name after '/'.
    spk_nam = spk_nam.split('/')[0]
    #Check whether the name string contains ' and '.
    names = spk_nam.split(' and ')
    #In the case of 'Joey and Ross', duplicate the records.
    for name in names:
        v = nam_ct_d.get(name)
        if v is None: nam_ct_d[name] = 1
        else: nam_ct_d[name] = v + 1
        n_dfv.append(np.array([name, *row[1: ]], dtype = object))
        #inner-for-end
    #for-end
#Reform the dataframe.
n_df = pd.DataFrame(n_dfv, columns = df.columns)
#Drop duplicates again (safer).
n_df.drop_duplicates(inplace = True)

In [6]:
#Order the names descendantly in their frequencies.
nam_order = np.flip(np.argsort(list(nam_ct_d.values())))
nam_desc = np.array(list(nam_ct_d.keys()), dtype = object)[nam_order]
#Encode the names.
nam_cod_d = OrderedDict()
for i, name in enumerate(nam_desc): nam_cod_d[name] = i
#Insert the encoded names.
n_df.insert(n_df.columns.get_loc('Episode') + 1, 'Speaker_coded', n_df['Speaker'].apply(lambda name: nam_cod_d[name]))
#Encode the emotions.
cod_emotion = LabelEncoder()
n_df.insert(n_df.columns.get_loc('Speaker_coded') + 1, 'Emotion_coded', cod_emotion.fit_transform(n_df['Emotion'].values))
#Drop the original 'Speaker' and 'Emotion' columns.
n_df.drop(columns = ['Speaker', 'Emotion'], inplace = True)
#Sorting the data.
n_df.sort_values(by = ['Season', 'Episode', 'StartTime_int'], ignore_index = True, inplace = True)
#Show the data.
n_df.head()

,Season,Episode,Speaker_coded,Emotion_coded,StartTime_int,EndTime_int,Utterance
0,1,1,5,4,79037,85417,"Alright, so I'm back in high school, I'm stand..."
1,1,1,11,4,85627,87169,"Oh, yeah. Had that dream."
2,1,1,5,6,87378,91465,"Then I look down, and I realize there's a phon..."
3,1,1,0,6,94928,95600,Instead of...?
4,1,1,5,4,95600,96892,That's right.

In [7]:
#Save the data file in csv format.
n_df.to_csv("emo_data.csv", header = True, index = False)
#Save the segmented data files by 'Season' and 'Episode' in csv format.
for (s, e), sub_df in n_df.groupby(['Season', 'Episode']):
    sub_df.to_csv("emo_data_s%02d_e%02d.csv" % (s, e), header = True, index = False)
    #for-end

In [8]:
#Display the encoding of 'Speaker'.
print("Speaker\tCode")
for k, v in nam_cod_d.items(): print(k, '\t', v)

Speaker	Code
Joey 	 0
Rachel 	 1
Ross 	 2
Phoebe 	 3
Monica 	 4
Chandler 	 5
Janice 	 6
Carol 	 7
Emily 	 8
Tag 	 9
Mona 	 10
All 	 11
Pete 	 12
Mark 	 13
Danny 	 14
Richard 	 15
Doug 	 16
Joanna 	 17
Mr. Treeger 	 18
Mr. Geller 	 19
Julie 	 20
Elizabeth 	 21
Mrs. Geller 	 22
Dr. Green 	 23
Phoebe Sr 	 24
Susan 	 25
Paul 	 26
Eric 	 27
Frank 	 28
Woman 	 29
Barry 	 30
Chip 	 31
Gunther 	 32
Kate 	 33
David 	 34
Joshua 	 35
Cassie 	 36
Charlie 	 37
Kristen 	 38
Mr. Tribbiani 	 39
Ben 	 40
Russell 	 41
Dina 	 42
The Casting Director 	 43
Katie 	 44
Julio 	 45
Policeman 	 46
Man 	 47
Jill 	 48
Lydia 	 49
Issac 	 50
Stanley 	 51
Kathy 	 52
The Interviewer 	 53
Receptionist 	 54
Guy 	 55
The Cooking Teacher 	 56
Janine 	 57
Mischa 	 58
Robert 	 59
Earl 	 60
Dr. Baldhara 	 61
Mike 	 62
Isabella 	 63
Mr. Heckles 	 64
Cliff 	 65
Chloe 	 66
Dana 	 67
Krista 	 68
Nurse 	 69
Duncan 	 70
Gary 	 71
Mr. Franklin 	 72
Kim 	 73
Shelley 	 74
Ursula 	 75
Megan 	 76
The Director 	 77
Jim 	 78
Larry 	 79
The Potential Roommate 	 80
Terry 	 81
Stage Director 	 82
Evil Bitch 	 83
Steve 	 84
Dr. Zane 	 85
The Smoking Woman 	 86
Student 	 87
Mindy 	 88
Fireman No. 3 	 89
Young Ethan 	 90
Flight Attendant 	 91
Joey's Hand Twin 	 92
The Fireman 	 93
Rick 	 94
Girl 	 95
Teacher 	 96
Melissa 	 97
Dr. Long 	 98
Director 	 99
Phoebe Sr. 	 100
Mrs. Green 	 101
Kristin 	 102
The Security Guard 	 103
The Museum Official 	 104
Fake Monica 	 105
Dr. Rhodes 	 106
Sarah 	 107
Bob 	 108
Nancy 	 109
Woman On Train 	 110
Allesandro 	 111
Stranger 	 112
Ronni 	 113
Dr. Miller 	 114
Trudie Styler 	 115
Paula 	 116
Dr. Drake Remoray 	 117
Kyle 	 118
Angela 	 119
Lorraine 	 120
Carl 	 121
Leslie 	 122
Mr. Burgin 	 123
Roger 	 124
Tour Guide 	 125
Jade 	 126
Jester 	 127
Bobby 	 128
Bonnie 	 129
The Instructor 	 130
The Head Librarian 	 131
Alice 	 132
The Lurker 	 133
The Food Critic 	 134
Maitre d' 	 135
Ms. McKenna 	 136
Hotel Clerk 	 137
Liam 	 138
Mr. Zelner 	 139
Mona's Date 	 140
Richard’s Date 	 141
Customer 	 142
Ticket Counter Attendant 	 143
Singer 	 144
Tom 	 145
Jane 	 146
Hitchhiker 	 147
The Vendor 	 148
Joanne 	 149
Supervisor 	 150
Annabelle 	 151
Tony 	 152
Hoshi 	 153
The Woman 	 154
Bernice 	 155
Charlton Heston 	 156
Caitlin 	 157
The Singing Man 	 158
Casey 	 159
Mr. Waltham 	 160
Older Scientist 	 161
Estelle 	 162
The Grip 	 163
Santos 	 164
Gerston 	 165
Cecilia 	 166
Another Scientist 	 167
Dr. Franzblau 	 168
The Guys 	 169
Hope 	 170
Jay Leno 	 171
Leader 	 172
Dr. Wesley 	 173
Airline Employee 	 174
Sick Bastard 	 175
Mr. Posner 	 176
Jason 	 177
PBS Volunteer 	 178
an 	 179
Marc 	 180
Fireman No. 2 	 181
Friend No. 2 	 182
Fireman No. 1 	 183
Dr. Oberman 	 184
Mrs. Burgin 	 185
Jake 	 186
Voice 	 187
Dr. Ledbetter 	 188
Sophie 	 189
3rd Customer 	 190
Kiki 	 191
Raymond 	 192
Both 	 193
Front Desk Clerk 	 194
Gary Collins 	 195
The Cigarette Guy 	 196
Janitor 	 197
Nurse #1 	 198
Nurse #2 	 199
Dr. Stryker Ramoray 	 200
Stephanie 	 201
Guy #1 	 202
Hombre Man 	 203
The Conductor 	 204
Waiter 	 205
Her-Friends 	 206
Aunt Lillian 	 207
The Acting Teacher 	 208
Mrs. Tedlock 	 209
Another Tour Guide 	 210
Boy in the Cape 	 211
Mrs. Chatracus 	 212
Burt 	 213
Doctor 	 214
Mrs. Waltham 	 215
Vince 	 216
Hold Voice 	 217
The Croupier 	 218
Jeannine 	 219
Friend No. 1 	 220
Petrie 	 221
Mrs. Tribbiani 	 222
Drunken Gambler 	 223
A Student 	 224
The Librarian 	 225
Helena 	 226
Paolo 	 227
Mrs. Lynch 	 228
Robbie 	 229
Stu 	 230
Emeril 	 231
Dr. Leedbetter 	 232
Lecturer 	 233
1st Customer 	 234
Message 	 235
The Presenter 	 236
2nd Customer 	 237
The Assistant Director 	 238
A Female Student 	 239
Commercial 	 240
Dr. Johnson 	 241
Stevens 	 242
Peter 	 243
Guru Saj 	 244
Wayne 	 245
The Dry Cleaner 	 246
Paleontologist 	 247
Professore Clerk 	 248
Sergei 	 249

In [9]:
#Display the encoding of 'Emotion'.
print("Emotion\tCode")
for i, s in enumerate(cod_emotion.classes_): print(s, '\t', i)

Emotion	Code
anger 	 0
disgust 	 1
fear 	 2
joy 	 3
neutral 	 4
sadness 	 5
surprise 	 6